services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lixin
      TZ: Asia/Shanghai
    command: --default-time-zone='+08:00' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
