services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lixin
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
